St/update seed
House-on-a-Rock/tjc-scheduling-server pull request #19
Opened 2020-10-09 02:01 UTC by showduhtung

2020-10-09 02:03 UTC, showduhtung commented
- A lot of the file changes is from abstracting out logic and making lots of new files from them
- Improved the script file
- Added more data to seed file
- got started on new tables (probably should've done it in a separate pull request)

2020-10-09 05:11 UTC, hchiam commented
Reviewed 75% of the files. It'll take me a while to review the rest of the bigger diffs. I see you're reworking some table relationships, but I'm not up-to-date on the DB setup, so hopefully @CedThen and/or @alan-mj-lin can double-check that stuff.

2020-10-09 05:17 UTC, hchiam requested changes

2020-10-09 05:17 UTC, hchiam commented on server/routes/notifications.ts
> +        const { requesteeUserId, task, type: swapRequestType } = request;
Where is `swapRequestType` defined? it's used 4 times in this file

2020-10-09 15:32 UTC, showduhtung commented on server/routes/notifications.ts
> +        const { requesteeUserId, task, type: swapRequestType } = request;
so this is a es6 thing where you can destructure and then rename it. 
```
const message = { greeting: 'Hello' };
const { greeting: renamedVariable }  = message;

console.log(renamedVariable + 'World')
// 'Hello World'
```

2020-10-09 15:33 UTC, showduhtung commented on server/routes/notifications.ts
> +        const { requesteeUserId, task, type: swapRequestType } = request;
so it's being defined in line 77

2020-10-09 16:32 UTC, hchiam commented on server/routes/notifications.ts
> +        const { requesteeUserId, task, type: swapRequestType } = request;
oh cool! i thought it was a type ahha

2020-10-11 18:29 UTC, hchiam requested changes

2020-10-11 18:29 UTC, hchiam commented on scripts/makeDatabase.js
> +/* eslint-disable no-plusplus */
fighting the linter i see :(
Suggestions:
1. add `"no-plusplus": "off"` in the .eslintrc (so i++ etc works inside basic for loops). Not sure why it's not covered by all the `recommended`s in `extends`.
2. This file looks like it's just for testing, but if you want to clean it up, you can replace the 2 offending `.map`s with `.forEach`, so you can remove `eslint-disable array-callback-return`
```suggestion
/* eslint-disable no-unused-vars */
/* eslint-disable @typescript-eslint/no-unused-vars */
```

2020-10-11 18:29 UTC, hchiam commented on scripts/makeDatabase.js
> +    databaseUsers.map((user, index) => {
This is what I mean. Here: 
```suggestion
    databaseUsers.forEach((user, index) => {
```

2020-10-11 18:29 UTC, hchiam commented on scripts/makeDatabase.js
> +    databaseRoles.map((role, index) => {
and here: 
```suggestion
    databaseRoles.forEach((role, index) => {
```

2020-10-11 18:29 UTC, hchiam commented on server/db/models/User.ts
>      };
Interesting. So Instead of directly associating user with role and task, you're associating user with user_role with task. Kinda like a linear `user -> user_role -> task` instead of parallel arrows `user -> (role, task)`.

2020-10-11 18:29 UTC, hchiam commented on server/routes/authentication.ts
> +                : ['User does not exist or is not verified', 401];
interesting. very concise and avoids using `let`

2020-10-11 18:29 UTC, hchiam commented on server/routes/requests.ts
> +            requesteeUserId: yourUserId,
i personally found the `my`s and `your`s a little ambiguous until I read this line. We could make it more obvious/boring with 
```suggestion
            requesteeUserId,
```
and then replace `your...` -> `requestee...` and `my...` -> `requester...` or `requesting...` (unless I have the POV backwards)

2020-10-11 18:29 UTC, hchiam commented on server/routes/requests.ts
> +        return request ? res.status(200) : res.status(404).send({ message: 'Swap request not found' });
the `DELETE` route isn't actually performing a delete for now, right?

2020-10-11 18:29 UTC, hchiam commented on server/routes/requests.ts
> +        return status === 202 ? res.status(status).json(request) : res.status(status).send({ message });
Maybe yes? If I understand correctly, the requestee currently can hit to "accept" _all_ requested task swaps from one requester _at once_, but currently the requestee _cannot_ "approve" all tasks from a requester all at once? I'm not super clear what the distinction between accept/approve is in this app. Is "accept" more like viewing, or are they both buttons but "approve" is more like hitting an "are you sure" confirmation button?

2020-10-11 18:29 UTC, hchiam commented on server/routes/tasks.ts
> +                    : ['Task not found', 404];
The `askingTeammate` is asking to give you to take over their task. So is this ternary backwards? Or are you sending a 200 success status if the task and user roles _can't_ be found because that means the id's haven't been swapped yet? Just checking.

2020-10-11 18:29 UTC, hchiam commented on server/routes/users.ts
> +        addedUser && (await db.Token.create({ userId: addedUser.id, token }));
I got this to pass `eslint server/routes/users.ts` in your branch:
```suggestion
        if (addedUser) await db.Token.create({ userId: addedUser.id, token });
```

2020-10-11 18:31 UTC, hchiam requested changes
Done reviewing. Note that there's a merge conflict buried at the bottom of the comments.

2020-10-13 16:41 UTC, showduhtung commented on scripts/makeDatabase.js
> +/* eslint-disable no-plusplus */
yeah.. some of these are real weird. I kept the .map and changed up eslintrc instead.

yeah you can disregard a lot of the stuff in this file. it'll never really be used for development, and theyre kinda just personal scripts im writing to help me generate files and data for seed files

2020-10-13 16:43 UTC, showduhtung commented on server/routes/authentication.ts
> +                : ['User does not exist or is not verified', 401];
yeah. I find it a lot cleaner to declare the constants on the spot, instead of through a huge mumbo jumbo of 'if else' statements

2020-10-13 16:49 UTC, showduhtung commented on server/db/models/User.ts
>      };
kinda. the way I see it, I see Role more as 'team', but.. people don't want me to change role to teams. So every team has many users, and every user is a part of many teams. The inbetween is that UserRole is essentially "Team member" that describes both the user and the team associated with them.

Before, task belonged to both a user and a role, and I thought this doesn't really make much sense when those data points already exists as UserRole. So I'm thinking that we can instead think that the task belongs to a particular "teammate."

2020-10-13 16:50 UTC, showduhtung commented on server/routes/requests.ts
> +            requesteeUserId: yourUserId,
haha very interesting, I changed it from requestee/requester to your/my because I thought it was clearer (also less wordy and thus cleaner), but as I'm hearing two voices say that requestee makes more sense, then I think that's the way to go.

2020-10-13 16:51 UTC, showduhtung commented on server/routes/requests.ts
> +        return request ? res.status(200) : res.status(404).send({ message: 'Swap request not found' });
correct.

2020-10-13 16:57 UTC, showduhtung commented on server/routes/requests.ts
> +        return status === 202 ? res.status(status).json(request) : res.status(status).send({ message });
so the `approve` attribute comes from church council. there're certain functions that cannot be swapped without church council approval (sermon speaking). 

but now that I think about it, I didn't really think much about the actual use cases of most of these routes. This pull request/ branch was dedicated to refactoring the code to be cleaner, leaner and just to check for bugs. 

So I think the answer to this is that we don't need to test for requestAll, maybe.. I'm ok with keeping this question in, just as a reminder for the future.

2020-10-13 17:03 UTC, showduhtung commented on server/routes/tasks.ts
> +                    : ['Task not found', 404];
Oops good call, I should've done `task && replacingTeammate && askingTeammate`

2020-10-13 17:03 UTC, showduhtung commented on server/routes/users.ts
> +        addedUser && (await db.Token.create({ userId: addedUser.id, token }));
haha thanks for finding these.

2020-10-13 17:26 UTC, merged