Schedule routes
House-on-a-Rock/tjc-scheduling-server pull request #25
Opened 2020-11-04 00:57 UTC by showduhtung

adds the first schedule api endpoint. also creates initial schedule models

2020-11-04 00:59 UTC, showduhtung commented
there's really only two files to look at:
`server/db/models/Services.ts`
and 
`server/routes/schedules.ts`

2020-11-05 05:36 UTC, hchiam requested changes

2020-11-05 05:36 UTC, hchiam commented on server/utilities/helperFunctions.ts
> +            exp: Math.floor(Date.now() / 1000) + expiresInMinutes * 60 * 60,
Remove the second `* 60`
`Date.now` is in ms / 1000 = in seconds
expiresInMinutes is in minutes * 60 = seconds, don't need the * 60 again.
seconds + (?) != seconds

2020-11-05 05:36 UTC, hchiam commented on server/utilities/helperFunctions.ts
> +    const convertedHour = hour === '12' ? 3600000 : 3600000 * parseInt(hour, 10);
I think you mean this?
```suggestion
    const convertedHour = hour === '12' ? 0 : 3600000 * parseInt(hour, 10);
```

2020-11-05 05:36 UTC, hchiam commented on server/utilities/helperFunctions.ts
> +    if (condition) return correctOrder(arr, lastIdx - 1, target, type);
You might not need the eslint-disable if you combine the exclusive conditions:
```suggestion
    if (!condition) {
        arr.splice(lastIdx + 1, 0, target);
        return arr;
    } else {
        return correctOrder(arr, lastIdx - 1, target, type);
    }
```

2020-11-05 05:36 UTC, hchiam commented on server/utilities/helperFunctions.ts
> +    let month = (monthIdx + 1).toString();
This is nitpicky and not urgent, but I think the `+ 1` to convert the index shouldn't be `zeroPaddingDates`'s responsibility

2020-11-05 05:36 UTC, hchiam commented on server/db/models/Services.ts
> +            allowNull: true,
Looks like you simply renamed the file, but should it be `allowNull: false,` here? I think [sequelize defaults `allowNull` (nullable) to true](https://sequelize.org/master/manual/model-basics.html?:~:text=Using%20sequelize.define%3A#using--a-href-----class-lib-sequelize-js-sequelize-html-instance-method-define---code-sequelize-define--code---a--:~:text=Using%20sequelize.define%3A).

2020-11-05 05:36 UTC, hchiam commented on server/routes/schedules.ts
> +                            const { name, start: startofService, end: endOfService, day: dayOfService } = service;
minor: camelCase on your alias `startofService` -> `startOfService`

2020-11-05 05:36 UTC, hchiam commented on server/routes/schedules.ts
> +                                        });
why are we mapping to get serviceData have the first (`[0]`) kvp of each task? I think `Object.keys()` and `Object.values()` don't guarantee order (not sure about the DB call though)

2020-11-05 19:12 UTC, showduhtung commented on server/utilities/helperFunctions.ts
> +            exp: Math.floor(Date.now() / 1000) + expiresInMinutes * 60 * 60,
haha tbh this is ok because this is for development purposes. The previous expiration token expired too fast when I'm testing things, and I'd rather a longer token while developing

2020-11-05 19:39 UTC, showduhtung commented on server/routes/schedules.ts
> +                                        });
so the reason why was because 
```
const tasksData = [{
  [contrivedDate(date)]: {
    data: { firstName, lastName, userId, role }
  }
}]
```
which meant that there'd be only one key and one value for each, but looking at this over, I realized that trying to organize the data in the tasksData makes no sense, when it can be done when mapping through tasksData to construct the serviceData


so I'll be fixing this to be more efficient

2020-11-05 19:43 UTC, showduhtung commented on server/utilities/helperFunctions.ts
> +    let month = (monthIdx + 1).toString();
hmm, but then you'd have to remember whenever you put them in. trade offs either way, but I think this looks cleaner. do you have another suggestion other than inputting `zeroPaddingDates(monthIdx + 1, dayIdx)`?

2020-11-05 19:46 UTC, showduhtung commented on server/utilities/helperFunctions.ts
> +    if (condition) return correctOrder(arr, lastIdx - 1, target, type);
agreed. one thing about your suggestion is that airbnb eslint (which is industry standard) doesn't like 
`else return` saying that else is redundant

so I'll be making it
```
  if (!condition) {
        arr.splice(lastIdx + 1, 0, target);
        return arr;
    }
    return correctOrder(arr, lastIdx - 1, target, type);
```

2020-11-06 00:28 UTC, hchiam commented on server/utilities/helperFunctions.ts
> +            exp: Math.floor(Date.now() / 1000) + expiresInMinutes * 60 * 60,
expiresInMinutes isn't really minutes anymore but it sounds like it prolly won't be too serious then. i'm guessing you're just changing it in one spot here, instead of doing a global edit of createToken uses

2020-11-06 00:32 UTC, hchiam commented on server/utilities/helperFunctions.ts
> +    let month = (monthIdx + 1).toString();
as long as we remember which way it is it should be fine. otherwise you have to read the function, but it's not that bad in this case.

2020-11-06 00:35 UTC, hchiam commented on server/utilities/helperFunctions.ts
> +    const convertedHour = hour === '12' ? 3600000 : 3600000 * parseInt(hour, 10);
i marked everything else as resolved. just this one thing

2020-11-06 00:37 UTC, hchiam requested changes
i marked everything as resolved except for the `0 : 3600000 * parseInt(hour, 10);`

2020-11-06 00:38 UTC, hchiam commented on server/utilities/helperFunctions.ts
> +    if (condition) return correctOrder(arr, lastIdx - 1, target, type);
yup sounds right

2020-11-06 04:26 UTC, merged