TSA-124 & TSA-132 delete button functionality with alerts
House-on-a-Rock/tjc-scheduling-server pull request #37
Opened 2020-12-25 21:28 UTC by alan-mj-lin

- addressed all comments from pull request #35 
- alert now uses proper material ui snackbar library
- alerts show on adding a schedule and deleting a schedule
- alerts should show on server errors as well (not tested)

2020-12-25 22:33 UTC, hchiam requested changes
Just a couple minor things with the `console.log`s, but otherwise LGTM! :+1:

We could have a better system for the `z-index`es, but I'd leave it for now since it's easy to clean up later if we really need to.

2020-12-25 22:33 UTC, hchiam commented on src/components/Schedule/ScheduleContainer.tsx
> +        console.log(response.data);
Remember to remove the [console log](https://memegenerator.net/img/instances/68620658/a-wild-consolelog-appeared.jpg) if it's not needed.

2020-12-25 22:33 UTC, hchiam commented on src/components/Schedule/ScheduleContainer.tsx
> +        console.log(alert !== null);
Remember to remove the [console log](https://memegenerator.net/img/instances/68620658/a-wild-consolelog-appeared.jpg) if it's not needed.

2020-12-25 22:35 UTC, hchiam commented on src/components/shared/Alert.tsx
> +      zIndex: 1000000, // too much?
A little unusual. I think this is greater than the loading spinner's `z-index`, but shouldn't be a problem.

2020-12-26 20:08 UTC, alan-mj-lin commented on src/components/shared/Alert.tsx
> +      zIndex: 1000000, // too much?
Alert isn't currently using that set of styles anyway haha

2020-12-27 22:04 UTC, CedThen commented on src/components/Schedule/ScheduleContainer.tsx
> +        onClick={() => setDeleteDialogOpen(!isDeleteDialogOpen)}
This isn't sticky to the tabs bar

2020-12-27 22:05 UTC, CedThen commented on src/components/Schedule/ScheduleContainer.tsx
> +          if (yesOrNo === true) {
clicking no doesn't do anything?
try using a ternary statement when u include the no option functionality

2020-12-27 22:06 UTC, CedThen commented on src/components/Schedule/ScheduleContainer.tsx
> +            setOpenedTabs([0]);
when there are no tabs left, schedule tabs seems to unmount. Can you make sure that it stays mounted, so that + button is still functional?

2020-12-27 22:10 UTC, CedThen commented on src/components/Schedule/ScheduleContainer.tsx
> +            onScheduleDelete(data[tabIdx].id, data[tabIdx].title);
You don't really need to make a function to just do this. Im guessing you followed onNewScheduleSubmit, can you also rewrite it so the await part is included inside the useMutation, and get rid of onNewScheduleSubmit?

2020-12-27 22:12 UTC, CedThen commented on src/components/Schedule/ScheduleContainer.tsx
> +            setDeleteDialogOpen(!isDeleteDialogOpen);
I think this should be name setIsDeleteDialogOpen
Maybe just set this to false since you're closing it, can potentially avoid bugs? @showduhtung whats the typical pattern here?

2020-12-27 22:13 UTC, CedThen commented on src/components/shared/Alert.tsx
> +function Alert(props: AlertProps) {
this function is unnecessary, I'd prefer if you removed this function and renamed the export back to alert

2020-12-27 22:15 UTC, CedThen commented on src/components/shared/Alert.tsx
> +        severity={alert.status === 'success' ? 'success' : 'error'}
You can type this to only be 'success' or 'error', and then just pass alert.status to severity instead of this ternary

2020-12-28 02:22 UTC, alan-mj-lin commented on src/components/Schedule/ScheduleContainer.tsx
> +            onScheduleDelete(data[tabIdx].id, data[tabIdx].title);
im not sure what you mean by putting await inside useMutation

2020-12-28 16:00 UTC, hchiam reviewed
Leaving it to Ted/Shaun. Not sure if a couple of Ted's comments are resolved yet.

2020-12-29 16:20 UTC, CedThen commented on src/components/Schedule/ScheduleContainer.tsx
>            if (yesOrNo === true) {
You can just do if (yesOrNo)

2020-12-29 17:14 UTC, showduhtung commented on src/components/Schedule/ScheduleContainer.tsx
> +          if (yesOrNo) {
maybe instead of yesOrNo, we can go with open. 

because !open = close, but !yesOrNo = yesOrNo

2020-12-29 17:19 UTC, alan-mj-lin commented on src/components/Schedule/ScheduleContainer.tsx
> +          if (yesOrNo) {
but yesOrNo doesn't correspond to whether the dialogue box is open or not. It corresponds to whether the user clicked yes or no on the dialogue. Yeah I agree yesOrNo isn't the best of variable names lol but it's just what I did in the moment hahaha

2020-12-29 17:28 UTC, showduhtung commented on src/components/Schedule/ScheduleContainer.tsx
> +          if (yesOrNo) {
ohohoh. then clicked works right? since right now it's arbitrary what the user clicked. 

so yesOrNo = clicked, and !yesOrNo = not clicked? correct me if I'm wrong
so then you could just use click, !click lol

whatever the case, you have my approval to merge

2020-12-29 17:33 UTC, alan-mj-lin commented on src/components/Schedule/ScheduleContainer.tsx
> +          if (yesOrNo) {
yesOrNo = true means the user clicked Yes. yesOrNo= false means the user clicked no.

2020-12-29 17:33 UTC, merged