St/restructure
House-on-a-Rock/tjc-scheduling-server pull request #39
Opened 2020-12-30 15:12 UTC by showduhtung

2020-12-30 16:55 UTC, alan-mj-lin requested changes
See comments

2020-12-30 16:55 UTC, alan-mj-lin commented on src/components/Auth/AuthProvider.tsx
> +  const [isLoggedIn, setIsLoggedIn] = useState(true);
Are we still working on a solution to this problem?

2020-12-30 16:55 UTC, alan-mj-lin commented on src/components/Auth/PrivateRoute.tsx
>  const validateUser = (condition: string, token): boolean => {
access and exp in validateUser are unused. Idk if it's being used in the future but if not probably good to get rid of it.

2020-12-30 16:55 UTC, alan-mj-lin commented on src/components/Schedule/Schedule.tsx
> +  function onSaveScheduleChanges() {
do you really need to write this as a separate function?

2020-12-30 16:55 UTC, alan-mj-lin commented on src/components/Schedule/Schedule.tsx
> +            onSaveScheduleChanges={onSaveScheduleChanges}
couldn't you just do onSaveScheduleChanges={setIsScheduleModified(false)}

2020-12-30 16:55 UTC, alan-mj-lin commented on src/components/Schedule/ScheduleTable.tsx
> +export const ScheduleTable = ({ title, hidden, children }: any) => {
eventually add proper typing for props?

2020-12-30 16:55 UTC, alan-mj-lin commented on src/components/Schedule/ScheduleTableBody.tsx
> +  //   const classes = useStyles();
a lot of dead code

2020-12-30 16:55 UTC, alan-mj-lin commented on src/components/Schedule/ScheduleTableHeader.tsx
> +export const ScheduleTableHeader = ({ header }: any) => {
proper typings for props

2020-12-30 16:55 UTC, alan-mj-lin commented on src/components/Schedule/ScheduleToolbar.tsx
> +}: any) => {
proper typings for props

2020-12-30 16:55 UTC, alan-mj-lin commented on src/components/Schedule/TableCell.tsx
> +    function renderOptions(option: any, state: any) {
I thought typing as any was bad practice

2020-12-30 16:55 UTC, alan-mj-lin commented on src/query/apis/schedules.ts
> +export const destroySchedule = (data: DeleteScheduleProps) =>
I think I like this

2020-12-30 16:55 UTC, alan-mj-lin commented on src/query/schedules.ts
> +// export const createNewSchedule = async (newInfo: NewScheduleData) =>
dead code

2020-12-30 16:55 UTC, alan-mj-lin commented on src/query/services.ts
> +export {}; // import { NewServiceData } from './apis/services';
what's with the empty export?

2020-12-30 16:55 UTC, alan-mj-lin commented on src/shared/types/models.ts
> +  scheduleId: number;
I originally typed it as string because when you get the json object that id is of a string type. Idk how using number affects the call.

2020-12-30 20:17 UTC, showduhtung commented on src/components/Auth/AuthProvider.tsx
> +  const [isLoggedIn, setIsLoggedIn] = useState(true);
nope

2020-12-30 20:19 UTC, showduhtung commented on src/components/Auth/PrivateRoute.tsx
>  const validateUser = (condition: string, token): boolean => {
oh no, access and expiration will definitely need to be used. i rushed to finish this branch so that you and ted can start working on it.

2020-12-30 20:21 UTC, showduhtung commented on src/components/Schedule/Schedule.tsx
> +  function onSaveScheduleChanges() {
this was ted's original function. in it was a note that said that there is an assumption many other things will change. the future of the changedTask ref will track changes for each tab. the save changes button will reflect it as well.

2020-12-30 20:21 UTC, alan-mj-lin commented on src/components/Auth/AuthProvider.tsx
> +  const [isLoggedIn, setIsLoggedIn] = useState(true);
do you want me to look into it?

2020-12-30 20:21 UTC, showduhtung commented on src/components/Schedule/Schedule.tsx
> +            onSaveScheduleChanges={onSaveScheduleChanges}
responded in a previous commentj

2020-12-30 20:21 UTC, showduhtung commented on src/components/Schedule/ScheduleTable.tsx
> +export const ScheduleTable = ({ title, hidden, children }: any) => {
oh thanks. yah i'll actually go ahead and do that now because why not

2020-12-30 20:22 UTC, showduhtung commented on src/components/Schedule/ScheduleTableBody.tsx
> +  //   const classes = useStyles();
actually it's not dead code but my commented out comments that includes code. the comments have notes and thoughts for a feature that ted and I were talking about, and I think it makes sense to add it here. but for now, it's a very reusable and functional component

2020-12-30 20:23 UTC, showduhtung commented on src/components/Schedule/ScheduleTableBody.tsx
> +  //   const classes = useStyles();
also, I'd argue that commented out code isn't actually dead, as it's not being read. unused code is dead

2020-12-30 20:24 UTC, showduhtung commented on src/components/Schedule/TableCell.tsx
> +    function renderOptions(option: any, state: any) {
it is.. a lot of this was ted's stuff.

2020-12-30 20:24 UTC, showduhtung commented on src/query/apis/schedules.ts
> +export const destroySchedule = (data: DeleteScheduleProps) =>
heh

2020-12-30 20:27 UTC, showduhtung commented on src/query/schedules.ts
> +// export const createNewSchedule = async (newInfo: NewScheduleData) =>
im keeping it for now, because there's currently a discrepancy with how i'm using query and apis. I'm using some endpoints directly from api, and then im' using some endpoints through and intermediary function via query. I haven't yet decided how it should be used, but once I make data handlers for the other containers, then a pattern should emerge. until then, this, as well as the `export {}` in services.ts will stay as reference for myself when i continue working on this

2020-12-30 20:28 UTC, showduhtung commented on src/query/services.ts
> +export {}; // import { NewServiceData } from './apis/services';
typescript won't compile because i have it required that every file must be a module. so empty files get flagged as not a module

2020-12-30 20:29 UTC, showduhtung commented on src/shared/types/models.ts
> +  scheduleId: number;
it doesn't really. but I've noticed that we're not being consistent with the id's throughout the app. i haven't had the brain power to go through them all and rewrite them as such. but yah maybe we should change so that the app expects the id to be a string. we just have to go through with a fine comb looking for these differences

2020-12-30 20:30 UTC, showduhtung commented on src/shared/types/models.ts
> +  scheduleId: number;
but if we can do it later in a different branch thatd be great because that's outside the scope of this pull request

2020-12-30 20:30 UTC, hchiam requested changes

2020-12-30 20:30 UTC, hchiam commented on package.json
> +    "react-query": "^3.5.0",
Why was package-lock.json removed? The `/src` folder has its own lock file and package.json.

2020-12-30 20:30 UTC, hchiam commented on src/components/Schedule/NewScheduleForm.tsx
> +      <h2>Create a new schedule</h2>
```suggestion
      <h2>Create A New Schedule</h2>
```
Capitalize the `<h2>`, to be consistent with NewServiceForm.js's "Add A New Event"

2020-12-30 20:30 UTC, hchiam commented on src/components/Auth/PrivateRoute.tsx
> +  const auth = useContext(AuthContext);
`useContext`. nice.

2020-12-30 20:30 UTC, hchiam commented on src/components/Schedule/NewScheduleForm.tsx
> +  onSubmit: (newScheduleData: NewScheduleData) => void;
much cleaner

2020-12-30 20:30 UTC, hchiam commented on src/components/Schedule/Schedule.tsx
> +// 4. Low priority but finding scheduleId and order is a pain the way I have it currently implemented because allScheduleData exists in tabs, but singular schedule data exist in schedules. Need to co
Don't forget to do these later, as separate [task(s)](https://tjc-scheduling.atlassian.net/jira/software/projects/TSA/boards/1?label=Web) or [issue(s)](https://github.com/House-on-a-Rock/tjc-scheduling-app/issues) or [PR(s)](https://github.com/House-on-a-Rock/tjc-scheduling-app/pulls).

2020-12-30 20:30 UTC, hchiam commented on src/components/Schedule/Schedule.tsx
> +        <CircularProgress />
nice! Pure CSS should have better perf than JS modifying the DOM, especially on slow connections. But using CircularProgress is more consistent with how we use Material-UI elsewhere, and easier to use in this case, it looks like.

2020-12-30 20:30 UTC, hchiam commented on src/components/Schedule/Schedule.tsx
> +      {data?.schedules && data?.users && !isLoading ? (
for easier reading, i'd "flip" the ternary condition ([de morgan](https://en.wikipedia.org/wiki/De_Morgan%27s_laws#cite_ref-3:~:text=the%20negation%20of%20a%20conjunction%20is%20the%20disjunction%20of%20the%20negations)) so we can move the shorter alternative output to be directly under the condition, like this:
```suggestion
      {!data?.schedules || !data?.users || isLoading ? (
          <CircularProgress />
      ) : (
          /* the longer, main schedule tabs stuff */
      )}
```
Instead of having the `<CircularProgress />` suddenly at the end.

2020-12-30 20:30 UTC, hchiam commented on src/components/Schedule/ScheduleTable.tsx
> +        '&:before': {
```suggestion
        '&:before': { // use a pseudo-element to cover left-side gap when scrolling
```
I forgot to comment this. When I scrolled items left, I could see items "peeking out" from behind the table on the left side of the table when you scroll. Used a CSS pseudo-element to cover that gap.

2020-12-30 20:30 UTC, hchiam commented on src/components/Schedule/ScheduleTable.tsx
> +        '&:after': {
```suggestion
        '&:after': { // use a pseudo-element to cover right-side gap when scrolling
```
I forgot to comment this. When I scrolled, there was a weird tiny gap that was showing up on the right side of the frozen columns. Used a CSS pseudo-element to cover that other gap.

2020-12-30 20:30 UTC, hchiam commented on src/components/Schedule/ScheduleTableBody.tsx
> +  //   const classes = useStyles();
@showduhtung are you keeping these here just in case we want to revert the JSX and/or reuse the `useStyles`?

2020-12-30 20:30 UTC, hchiam commented on src/components/Schedule/TableCell.tsx
> +    function renderOptions(option: any, state: any) {
prolly WIP

2020-12-30 20:30 UTC, hchiam commented on src/components/Schedule/TableCell.tsx
> +      // would like this to autosize so each option is just a single line
To do this, `width: '100%',` on each option might work. 
If that doesn't work, try making the parent use `display: 'flex'` and each child have `flex: 1`

2020-12-30 20:30 UTC, hchiam commented on src/components/Schedule/utilities.ts
> +  const convertedMin = 60000 * parseInt(min, 10);
Good catch. The `parseInt` radix could become octal when the hour/min strings start with 0 ([in older browsers](https://www.w3schools.com/jsref/jsref_parseint.asp#main:~:text=This%20feature%20is%20deprecated) - now [all browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#Browser_compatibility:~:text=Parses%20leading%2Dzero%20strings%20as%20decimal%2C%20not%20octal) default to decimal in this edge case).

2020-12-30 20:30 UTC, hchiam commented on src/query/apis/schedules.ts
> +export const destroySchedule = (data: DeleteScheduleProps) =>
much cleaner

2020-12-30 20:30 UTC, hchiam commented on src/shared/styles/theme.js
> +    '&:hover': {
why is this removed? having a `&:focus` style makes it more obvious to people using screen readers when they navigate tabs by hitting the `tab` key, if they can't use a touchscreen or a mouse to hover (a11y)

2020-12-30 20:36 UTC, hchiam commented on src/components/Schedule/TableCell.tsx
> +      // would like this to autosize so each option is just a single line
Or leave this to another task/ticket.

2020-12-30 20:36 UTC, showduhtung commented
hey @alan-mj-lin @CedThen @hchiam , so just a note of this branch- this branch is NOT finished. there're no data handlers or containers for templates/team/members yet. this pull request is meant to get everyone moved off of the old schedule structure to this new and improved one. This pull request is also meant to be a model for how the other containers will look like- how data is handled in a high level component, followed by a container component that manages ui state, followed by a series of functional components. 

I may be missing some key things like typescript, CSS-issues, features that I glossed over while merging the previous one with this one, so if you can help me with that, where I've missed that'd be great. Typescript and CSS-issues can be finished in another branch, but if I'm missing key features that was previously made that you feel is necessary here, lmk

2020-12-30 20:54 UTC, showduhtung commented on src/components/Auth/AuthProvider.tsx
> +  const [isLoggedIn, setIsLoggedIn] = useState(true);
oh oh oh, do you mean the whole express redirecting the user to the react app?
Hmmm, so I had 2 reasons why I gave up on this. 
1) It's not that high of a security risk. I've talked to Ian about this- even if the user can "log themselves in", and even if they can forge themselves a token that bypasses them through `<PrivateRoute />`, they still need a valid token to retrieve any data to display any ui elements. Sure they can get html elements, but the data is protected. (Will need to confirm at a later date).

2) I think the solution to have Express reroute a React app only works if the React app and the Express app live on 2 different ports as completely separate apps. For @CedThen's sake (jk and all of ours), I have split this back up into two different apps, because the developer experience is majorly sucking. But when we are ready to push this to production, we will be merging the 2 apps BACK into 1 lol.. but this is for the sake of cost. I'm not 100% aware of the cost, but my guess is that hosting 2 apps cost 2x more than 1 app. Or at least around that number. Not all apps should be on one port- big businesses that have high scaling needs need their apps on separate ports, but because we don't have a fleet of apps, converging our webapp and serverapp into 1 is the most cost efficient. And I think this breaks the "redirect" method because of these lines in `server/index.ts`
```

const port = process.env.PORT || 8081;
const app: express.Application = express();
const DIST_DIR = path.join(__dirname, '../dist/');
const HTML_FILE = path.join(DIST_DIR, 'index.html');

app.use(express.static(DIST_DIR));
app.use('/api', require(...));

app.use('*', (req, res) => { ****
   console.log('sending file');
   res.sendFile(path.join(__dirname, '..', 'dist/index.html'));
});
```

2020-12-30 21:02 UTC, showduhtung commented on src/components/Auth/AuthProvider.tsx
> +  const [isLoggedIn, setIsLoggedIn] = useState(true);
notice in the line where *, and ** are. Those blocks of code are commented out in our current app but in production, we want these code blocks uncommented out to tell our express serverapp to not only serve the web-server, but to statically serve the webpacked files of our ReactApp. 

Now when a `res.redirect('localhost:ReactAppPort8080')` is made, if our apps were separated, it has no problems redirect the app to that url. But when the apps are converged, we'd make the `redirect` to itself- `res.redirect('localhost:ReactAppAndServerPort8080')`, sending it to:
```
app.use('*', (req, res) => { 
   res.sendFile(path.join(__dirname, '..', 'dist/index.html'));
});
```
And then all it receives is a blank page. 
Honestly, I'm totally down if you can figure this out and see where I'm wrong. You'll probably need to play around with a different fullstack app that has both backend and frontend on the same port. But if you don't want, also ok

2020-12-30 21:02 UTC, showduhtung commented on src/components/Auth/PrivateRoute.tsx
> +  const auth = useContext(AuthContext);
yee. 2nd time using it ever. but i think it's kinda magical

2020-12-30 21:03 UTC, showduhtung commented on src/components/Auth/PrivateRoute.tsx
> +  const auth = useContext(AuthContext);
but I think people can also find themselves too reliant on using it everywhere

2020-12-30 21:05 UTC, showduhtung commented on src/components/Schedule/NewScheduleForm.tsx
> +  onSubmit: (newScheduleData: NewScheduleData) => void;
i love typescript. both informational and cleaner

2020-12-30 21:08 UTC, showduhtung commented on src/components/Schedule/Schedule.tsx
> +      {data?.schedules && data?.users && !isLoading ? (
Oo, what's the reasoning behind this? Ted and I were talking about how while developing, it's a tad bit annoying when there's much fluff nearer to the top.

2020-12-30 21:12 UTC, showduhtung commented on src/components/Schedule/Schedule.tsx
> +        <CircularProgress />
Oh honestly this is just a temporary thing. I haven't really looked into how your showLoadingSpinner actually works. We can continue to compare the differences. I also noticed that the login screen wasn't changed away from CircularProgress that I implemented there, so we can also change it there as well.

2020-12-30 21:13 UTC, showduhtung commented on src/components/Schedule/ScheduleTable.tsx
> +        '&:before': {
sure! will add

2020-12-30 21:13 UTC, showduhtung commented on src/components/Schedule/utilities.ts
> +  const convertedMin = 60000 * parseInt(min, 10);
typescript caught tbh

2020-12-30 21:15 UTC, showduhtung commented on src/query/apis/schedules.ts
> +export const destroySchedule = (data: DeleteScheduleProps) =>
wait you like the name "destroySchedule" or that I'm showing that we don't really need to destructure the data, just to restructure it later. Because destroySchedule sounds awesome

2020-12-30 21:19 UTC, showduhtung commented on src/shared/styles/theme.js
> +    '&:hover': {
material ui already has a `&:focus` styling with the underline underneath. to me, on the desktop it looks really confusing when the page opens and looks like this indicating that the first tab is selected:
![Screen Shot 2020-12-30 at 4 16 51 PM](https://user-images.githubusercontent.com/35239938/103381670-70192280-4aba-11eb-926a-d5a2cb28328c.png)

to this new kind of indicator that a tab is selected.
![Screen Shot 2020-12-30 at 4 18 48 PM](https://user-images.githubusercontent.com/35239938/103381752-b66e8180-4aba-11eb-85a4-778b9c8c19d7.png)

2020-12-30 21:20 UTC, showduhtung commented on src/shared/styles/theme.js
> +    '&:hover': {
![Screen Shot 2020-12-30 at 4 20 02 PM](https://user-images.githubusercontent.com/35239938/103381817-e027a880-4aba-11eb-866d-2d9b36564439.png)
This picture to me feels consistent with the first picture

2020-12-30 21:22 UTC, showduhtung commented on package.json
> +    "react-query": "^3.5.0",
err I have no clue. But I don't think it's a breaking error?

2020-12-30 21:28 UTC, showduhtung commented on src/components/Schedule/TableCell.tsx
> +    function renderOptions(option: any, state: any) {
oh I mean, yes some of it was ted, but also some of it was mine and yes WIP haha. ted actually wanted to go ahead and try his hand at rewriting and managing all the typescript stuff, but I'm gonna steal some of that from him

2020-12-30 21:29 UTC, showduhtung commented on src/components/Auth/PrivateRoute.tsx
>  const validateUser = (condition: string, token): boolean => {
access- there will be more usages of the PrivateRoute to distinguish admin users and other users
exp- definitely needs to be implemented here in PrivateRoute

2020-12-30 22:17 UTC, hchiam commented on src/shared/styles/theme.js
> +    '&:hover': {
ah ok lgtm

2020-12-30 22:38 UTC, hchiam commented on src/components/Schedule/Schedule.tsx
> +      {data?.schedules && data?.users && !isLoading ? (
we can leave it as-is. i'd say it's fine either way, or depends. maybe i'm overapplying a rule, but it's like moving short guard clauses to the top of functions. 

Instead of wondering what the else condition is, readers know immediately - this makes sense when the alternate condition is really short. So instead of this:

```js
if (condition) {
  // long
  // long
  // long
  // long
  // long
  // ...
} else { // huh? scroll back up to find the matching brace
  // short
}
```

and replace that with this:

```js
if (!condition) {
  // short
} else {
  // long
  // long
  // long
  // long
  // long
}
```

but thinking about it from the other point of view:

```js
if (condition) {
  // main
  // happy
  // path
  // goes
  // here
} else {
  // edge case you don't usually care about
}
```

2020-12-31 00:47 UTC, showduhtung commented on src/components/Schedule/Schedule.tsx
> +      {data?.schedules && data?.users && !isLoading ? (
hmm this makes sense to me. @CedThen what do you think? If you're ok with it, I'll change it, and we'll follow by these comments, if not also ok

2020-12-31 03:06 UTC, alan-mj-lin commented on src/query/apis/schedules.ts
> +export const destroySchedule = (data: DeleteScheduleProps) =>
both

2020-12-31 15:56 UTC, hchiam approved these changes

2020-12-31 16:10 UTC, alan-mj-lin approved these changes

2020-12-31 17:35 UTC, CedThen commented on src/query/apis/services.ts
> +const secretIp = 'http://127.0.0.1:8081';
not so secret is it now

2021-01-01 15:03 UTC, merged