TSA-136 migrate teams to container logic
House-on-a-Rock/tjc-scheduling-server pull request #45
Opened 2021-01-09 23:09 UTC by alan-mj-lin

- teams now rendered based on data queries
- server updates to get mobile app to login properly
- dragging and dropping for teams edit does not yet interact with the database to save changes

2021-01-10 14:55 UTC, hchiam requested changes
just `console.log`s, otherwise lgtm

2021-01-10 14:55 UTC, hchiam commented on server/routes/tasks.ts
> +    // }
are we saving this for a later subtask?

2021-01-10 14:55 UTC, hchiam commented on server/routes/user-roles.ts
> +      console.log(userRoles[0].role.name);
Remember to remove the [console log](https://memegenerator.net/img/instances/68620658/a-wild-consolelog-appeared.jpg) if it's not needed.

2021-01-10 14:55 UTC, hchiam commented on server/routes/user-roles.ts
> +      console.log(formattedData);
Remember to remove the [console log](https://memegenerator.net/img/instances/68620658/a-wild-consolelog-appeared.jpg) if it's not needed.

2021-01-10 15:13 UTC, alan-mj-lin commented on server/routes/tasks.ts
> +    // }
someone confirm @showduhtung @CedThen that the Tasks table shouldn't have a churchId column. It was blocking the mobile app from login in so I commented it out. My version of the database doesn't have churchId in the Task table.

2021-01-12 20:24 UTC, CedThen commented on server/routes/tasks.ts
> +    // }
yup, no churchId column in the tasks table

2021-01-13 00:45 UTC, hchiam approved these changes
LGTM! :+1:

2021-01-18 02:45 UTC, hchiam requested changes
It looks like you tested it, so just minor things from me.

2021-01-18 02:45 UTC, hchiam commented on src/components/Teams/DroppableTeamMemberList.tsx
> +      setMemberInput({ ...memberInput, error: 'User does not exist' });
why is one `members.find` and the other `!users.find`? superficially, i don't see why it's not `members` and `!members`, or `users` and `!users`.
Or is it clearer if the first error message is changed to `'User is already listed as a team member'`?

2021-01-18 02:45 UTC, hchiam commented on src/components/Teams/services.tsx
> +  console.log(member);
Remember to remove the [console log](https://memegenerator.net/img/instances/68620658/a-wild-consolelog-appeared.jpg) if it's not needed.

2021-01-18 02:45 UTC, hchiam commented on src/container/Teams/Teams.tsx
> +  console.log(userData, teams.data);
Remember to remove the [console log](https://memegenerator.net/img/instances/68620658/a-wild-consolelog-appeared.jpg) if it's not needed.

2021-01-18 02:45 UTC, hchiam commented on server/routes/tasks.ts
> +    // if (churchId) searchArray.push({ churchId });
`churchId` isn't used elsewhere in this scope. Are you leaving this line commented out just in case we change our mind?

2021-04-29 00:11 UTC, closed without merging