Tc/manipulate events
House-on-a-Rock/tjc-scheduling-server pull request #47
Opened 2021-01-12 19:19 UTC by CedThen

In this PR, we can now add/remove events and services, and the autocompletes will display the correct options when a role assignment changes. 

Changes made are only local for now, I think in maybe 2 more PR it should be fully functional and can update the DB properly.

2021-01-12 19:20 UTC, CedThen commented on scripts/database/events.ts
> -    displayTime: true,
This logic is handled client side now

2021-01-13 00:51 UTC, hchiam commented
@CedThen I fixed a minor merge conflict for you. For some reason GitHub couldn't figure out that I simply added a class onto `ScheduleContainer`. https://github.com/House-on-a-Rock/tjc-scheduling-app/pull/47/commits/e0b7c7af978eb9b34638565aab916b219b05ffbc

2021-01-13 00:55 UTC, hchiam commented on src/query/apis/services.ts
> +  console.log('serviceInfo', serviceInfo);
Remember to remove the [console log](https://memegenerator.net/img/instances/68620658/a-wild-consolelog-appeared.jpg) if it's not needed.

2021-01-13 00:55 UTC, hchiam commented on src/query/apis/teams.ts
> +  return axios.get(`${secretIp}/api/roles?churchId=${churchId}`);
dead code?

2021-01-13 04:13 UTC, CedThen commented on src/query/apis/teams.ts
> +  return axios.get(`${secretIp}/api/roles?churchId=${churchId}`);
howard you have the eyes of a hawk, spotting all this code i've forgotten about

2021-01-14 03:21 UTC, hchiam commented on src/components/Schedule/TimeCell.tsx
> +  // }, [display]);
dead code?

2021-01-14 04:20 UTC, hchiam requested changes

2021-01-14 04:20 UTC, hchiam commented on src/container/Schedules/ScheduleContainer.tsx
> +        {dataModel.schedules.map((schedule: ScheduleTableInterface, scheduleIndex) => {
```suggestion
        {dataModel.schedules?.map((schedule: ScheduleTableInterface, scheduleIndex) => {
```
Otherwise I get a `dataModel.schedules is undefined` error.

2021-01-14 04:20 UTC, hchiam commented on src/container/Schedules/ScheduleContainer.tsx
> +    const target = dataClone.schedules[tab].services;
I get that this is still a WIP, but just an FYI in case: I'm getting `Uncaught TypeError: dataClone.schedules is undefined` when the schedule tab has no services on it to begin with. I ran `npm run seed` in the root folder in your branch. Is it working for you when you try to add the first service to a schedule?

2021-01-14 04:20 UTC, hchiam commented on src/components/Schedule/useAutocompleteHook.tsx
> +export const useAutoCompleteHook = (
Nice!  A custom hook.

2021-01-14 04:20 UTC, hchiam commented on src/container/Schedules/ScheduleContainer.tsx
> +    return templateChanges.current.changesSeed--;
sounds hacky (using a negative number to track change count? while also making it the only negative ID in the DB to make it easier to find it in the DB?) but I assume this'll get cleaned up later since this PR is a first pass.

2021-01-14 04:20 UTC, hchiam commented on src/container/Schedules/ScheduleContainer.tsx
> +      </Dialog> */}
this is all commented out. dead code i presume?

2021-01-14 04:20 UTC, hchiam commented on src/container/Schedules/utilities.ts
> +// autocomplete cell functions
this comment could get confusing if we accidentally add unrelated functions in between. maybe in one of the next PRs we can split/group these out into an `autocompleteUtilities.ts` and 
```js
import {
  extractRoleIds,
  getRoleOptionLabel,
  getUserOptionLabel,
  extractTeammateIds,
  teammates,
  blankTeammate,
  createBlankTask,
  createBlankEventCells,
  createBlankEvent,
  roleDisplay,
} from './autocompleteUtilities';
```

2021-01-14 04:20 UTC, hchiam commented on src/container/Schedules/utilities.ts
> +const createBlankTask = (seedFx) => {
```suggestion
const createBlankTask = (seedFx: () => {}) => {
```
to avoid errors, since `seedFx` will only be used as a function, and with no parameters.

2021-01-14 04:20 UTC, hchiam commented on src/container/Schedules/utilities.ts
> +    // 2 (the columns for time/duty) is hardcoded here
Explanatory variable to replace comment and magic number:
```suggestion
  const afterTimeAndDutyColumns = 2;
  for (let i = afterTimeAndDutyColumns; i < cellLength; i++) {
```

2021-01-14 16:03 UTC, CedThen commented on src/container/Schedules/ScheduleContainer.tsx
> +      </Dialog> */}
I think it might be used in the future, so i'm leaving it commented out instead of removing completely

2021-01-14 16:07 UTC, CedThen commented on src/container/Schedules/ScheduleContainer.tsx
> +    const target = dataClone.schedules[tab].services;
good catch, added some error handling to catch that

2021-03-19 03:45 UTC, showduhtung commented on src/components/Schedule/DutyAutocomplete.tsx
> +  const tableCellClass = isCellModified ? classes.modified : classes.cell;
I feel like I see this more common inside className={}

General thought is no need to go and create constants unless they're used a lot. Takes storage.

2021-03-19 03:47 UTC, showduhtung commented on src/components/Schedule/DutyAutocomplete.tsx
> +  extractOptionId?: (data: any) => number[];
did this method have to be passed in via props? if it's just a pure function, it's probably a good idea to keep it as a utility service or something

2021-03-19 04:56 UTC, showduhtung commented
I noticed that in both autocomplete cells (TasksAutocomplete) and (DutyAutocomplete) you didn't handle inputValue. Was this intentional? I think iirc, we had a difference of opinion here if we should or not, and how we'd manage it because of cell focus and whatnot. If this was intentional, then yeah it's all good but I think it'd be cool to add

2021-03-19 05:00 UTC, showduhtung commented
This isn't in this PR but I found a bit of inconsistencies in your methods:

onTaskChange:
```
dataClone.schedules[tab].services[serviceIndex].events[rowIndex].cells[columnIndex].userId = newAssignee;
setDataModel(dataClone);
```

onAssignedRoleChange:
```
const targetEvent = dataClone.schedules[tab].services[serviceIndex].events[rowIndex];
targetEvent.roleId = newRoleId;
setDataModel(dataClone);
```

Does the onAssignedRoleChange work the same way as the first one? My guess is that targetEvent points a reference to dataClone.{...}, and then updates so should be okay?

2021-03-19 16:54 UTC, CedThen commented on src/components/Schedule/DutyAutocomplete.tsx
> +  const tableCellClass = isCellModified ? classes.modified : classes.cell;
made suggested change

2021-03-19 16:55 UTC, CedThen commented on src/components/Schedule/DutyAutocomplete.tsx
> +  extractOptionId?: (data: any) => number[];
moved these to imports instead of props

2021-03-19 17:10 UTC, merged