Tc/bug hunting
House-on-a-Rock/tjc-scheduling-server pull request #67
Opened 2021-05-05 03:52 UTC by CedThen

2021-05-06 18:17 UTC, showduhtung commented on server/routes/schedules.js
> +      order: [['id', 'ASC']],
is it not already default to ascending ids?

2021-05-06 18:17 UTC, showduhtung commented on server/routes/schedules.js
> +      order: [['id', 'ASC']],
same as previous comment

2021-05-06 18:39 UTC, showduhtung commented on src/components/Schedule/EditServiceForm.jsx
> +    if (!result.destination || result.destination === result.source) {
oh you know what, gotta be careful about using numbers as truthy values. 
js interprets `!0` as `true`, and since we're using index, some index is probably `0`.

2021-05-06 18:53 UTC, showduhtung commented on src/components/Schedule/EditServiceForm.jsx
> +    if (!result.destination || result.destination === result.source) {
this is really weird that you say it works, because I feel like this statement will fail a lot. 
![Screen Shot 2021-05-06 at 2 52 57 PM](https://user-images.githubusercontent.com/35239938/117350602-bfad9780-ae7a-11eb-9d7b-3fdef921a06d.png)

2021-05-06 19:25 UTC, showduhtung requested changes

2021-05-06 19:25 UTC, showduhtung commented on src/components/Schedule/EditServiceForm.jsx
> +    if (!result.destination || result.destination === result.source) {
I think you should take a closer look at what the result objects look like to make an accurate `if` statement

2021-05-06 19:25 UTC, showduhtung commented on src/components/Schedule/ScheduleContainer.jsx
> +    setViewedTab(newTab);
maybe you can change viewedTab to currentTab. just a suggestion

2021-05-06 19:25 UTC, showduhtung commented on src/components/Schedule/ScheduleContainer.jsx
> +    setOpenedTabs((t) => [...t, newTab]);
for openedTabs, will we want the opened tabs to persist when we go throughout the app? maybe we wanna use useRef? (may not have any effect tbh since I think when the component unmount, the ref also resets)

2021-05-06 19:25 UTC, showduhtung commented on src/components/Schedule/ScheduleContainer.jsx
> +      const clone = [...t];
this looks like it's always going to be organized in ascending order? like it looks like you're splicing the array to insert a tab inside. couldnt you just make a typical sort function that inserts an item in a list?

2021-05-06 19:25 UTC, showduhtung commented on src/components/Schedule/ScheduleMain.jsx
> +// contextmenu b r o k e n, but do we need it?
yes

2021-05-06 19:25 UTC, showduhtung commented on src/components/Schedule/ScheduleMain.jsx
> +// contextmenu b r o k e n, but do we need it?
but we don't have to have it for our first MVP.

2021-05-06 19:25 UTC, showduhtung commented on src/components/Schedule/Table.jsx
> +                                  style={{
can we remove inline stylings as much as possible?

2021-05-06 20:51 UTC, CedThen commented on server/routes/schedules.js
> +      order: [['id', 'ASC']],
it does not, i had cases where i got the data out of order, which is why i included this

2021-05-07 00:40 UTC, CedThen commented on src/components/Schedule/ScheduleContainer.jsx
> +    setOpenedTabs((t) => [...t, newTab]);
i think data is cached by react-query anyways. after testing it, there is no load screen when switching away then back to a schedule with already loaded tabs

2021-05-07 02:09 UTC, merged